### ISSUE TITLE
Weight difference not squared

### ISSUE THREAD

**Issue by gyglim** [rahafaljundi/MAS#3]
According to the paper the weight difference is squared when computing the loss, cf. Eq. (3)

In the code however it looks like it's just the difference:
https://github.com/rahafaljundi/MAS-Memory-Aware-Synapses/blob/c3e6a855cdde588fb74aeb876f84340eb6090ad5/MAS_to_be_published/MAS_utils/MAS_based_Training.py#L80

That would mean that a negative difference would lead to a negative penalty! Is that a bug or am I missing something?

**Comment by rahafaljundi** [comment]
Hi Michael,

The difference that I have in my code is the gradient of the L2.

Best,
Rahaf

**Comment by gyglim** [comment]
Hi Rahaf

Ah, I see, you directly compute gradient of the loss, not the loss. Got it :).
Thanks for the clarification

Cheers,
Michael
